package com.exception;

public class ExceptionDemo {
	public static void main(String args[]) {
		try {
			int a[]=new int[5];
			a[5]=20/0;
		}catch(ArithmeticException e) {
			System.out.println("divide by zero called");
		}catch(ArrayIndexOutOfBoundException e) {
			System.out.println("Check length of array");
		}
		
	}

}
